/// One Tesseract-recognizable language.
class TesseractLanguage {
  const TesseractLanguage(this.code, this.name);

  /// The 3-letter (or 3+suffix) code Tesseract/tessdata_fast uses as the
  /// filename, e.g. "eng" → eng.traineddata, "aze_cyrl" → aze_cyrl.traineddata.
  final String code;
  final String name;
}

/// Curated from Tesseract's official language set
/// (https://github.com/tesseract-ocr/tessdata_fast) — real spoken/written
/// languages only. Deliberately excludes script-detection/orientation files
/// (osd, equ) and narrow historical script variants (old-spelling, Fraktur,
/// vertical-text duplicates) to keep the picker focused and unambiguous.
///
/// English is pinned first — it's the only language bundled with the app
/// (assets/tessdata/eng.traineddata), so it's always available offline with
/// zero download. Everything else downloads once, on demand, the first time
/// it's selected, and is cached on-device permanently after that.
const List<TesseractLanguage> kTesseractLanguages = [
  TesseractLanguage('eng', 'English'),
  TesseractLanguage('afr', 'Afrikaans'),
  TesseractLanguage('amh', 'Amharic'),
  TesseractLanguage('ara', 'Arabic'),
  TesseractLanguage('asm', 'Assamese'),
  TesseractLanguage('aze', 'Azerbaijani'),
  TesseractLanguage('aze_cyrl', 'Azerbaijani (Cyrillic)'),
  TesseractLanguage('eus', 'Basque'),
  TesseractLanguage('bel', 'Belarusian'),
  TesseractLanguage('ben', 'Bengali'),
  TesseractLanguage('bos', 'Bosnian'),
  TesseractLanguage('bre', 'Breton'),
  TesseractLanguage('bul', 'Bulgarian'),
  TesseractLanguage('mya', 'Burmese'),
  TesseractLanguage('cat', 'Catalan'),
  TesseractLanguage('ceb', 'Cebuano'),
  TesseractLanguage('chr', 'Cherokee'),
  TesseractLanguage('chi_sim', 'Chinese (Simplified)'),
  TesseractLanguage('chi_tra', 'Chinese (Traditional)'),
  TesseractLanguage('cos', 'Corsican'),
  TesseractLanguage('hrv', 'Croatian'),
  TesseractLanguage('ces', 'Czech'),
  TesseractLanguage('dan', 'Danish'),
  TesseractLanguage('div', 'Dhivehi'),
  TesseractLanguage('nld', 'Dutch'),
  TesseractLanguage('dzo', 'Dzongkha'),
  TesseractLanguage('epo', 'Esperanto'),
  TesseractLanguage('est', 'Estonian'),
  TesseractLanguage('fao', 'Faroese'),
  TesseractLanguage('fil', 'Filipino'),
  TesseractLanguage('fin', 'Finnish'),
  TesseractLanguage('fra', 'French'),
  TesseractLanguage('fry', 'Frisian'),
  TesseractLanguage('glg', 'Galician'),
  TesseractLanguage('kat', 'Georgian'),
  TesseractLanguage('deu', 'German'),
  TesseractLanguage('ell', 'Greek'),
  TesseractLanguage('guj', 'Gujarati'),
  TesseractLanguage('hat', 'Haitian Creole'),
  TesseractLanguage('heb', 'Hebrew'),
  TesseractLanguage('hin', 'Hindi'),
  TesseractLanguage('hun', 'Hungarian'),
  TesseractLanguage('isl', 'Icelandic'),
  TesseractLanguage('ind', 'Indonesian'),
  TesseractLanguage('gle', 'Irish'),
  TesseractLanguage('ita', 'Italian'),
  TesseractLanguage('jpn', 'Japanese'),
  TesseractLanguage('jav', 'Javanese'),
  TesseractLanguage('kan', 'Kannada'),
  TesseractLanguage('kaz', 'Kazakh'),
  TesseractLanguage('khm', 'Khmer'),
  TesseractLanguage('kir', 'Kirghiz'),
  TesseractLanguage('kor', 'Korean'),
  TesseractLanguage('kmr', 'Kurdish (Kurmanji)'),
  TesseractLanguage('lao', 'Lao'),
  TesseractLanguage('lat', 'Latin'),
  TesseractLanguage('lav', 'Latvian'),
  TesseractLanguage('lit', 'Lithuanian'),
  TesseractLanguage('ltz', 'Luxembourgish'),
  TesseractLanguage('mkd', 'Macedonian'),
  TesseractLanguage('msa', 'Malay'),
  TesseractLanguage('mal', 'Malayalam'),
  TesseractLanguage('mlt', 'Maltese'),
  TesseractLanguage('mri', 'Maori'),
  TesseractLanguage('mar', 'Marathi'),
  TesseractLanguage('mon', 'Mongolian'),
  TesseractLanguage('nep', 'Nepali'),
  TesseractLanguage('nor', 'Norwegian'),
  TesseractLanguage('oci', 'Occitan'),
  TesseractLanguage('ori', 'Oriya'),
  TesseractLanguage('pan', 'Punjabi'),
  TesseractLanguage('fas', 'Persian'),
  TesseractLanguage('pol', 'Polish'),
  TesseractLanguage('por', 'Portuguese'),
  TesseractLanguage('pus', 'Pashto'),
  TesseractLanguage('que', 'Quechua'),
  TesseractLanguage('ron', 'Romanian'),
  TesseractLanguage('rus', 'Russian'),
  TesseractLanguage('san', 'Sanskrit'),
  TesseractLanguage('gla', 'Scottish Gaelic'),
  TesseractLanguage('srp', 'Serbian'),
  TesseractLanguage('srp_latn', 'Serbian (Latin)'),
  TesseractLanguage('snd', 'Sindhi'),
  TesseractLanguage('sin', 'Sinhala'),
  TesseractLanguage('slk', 'Slovak'),
  TesseractLanguage('slv', 'Slovenian'),
  TesseractLanguage('spa', 'Spanish'),
  TesseractLanguage('sqi', 'Albanian'),
  TesseractLanguage('sun', 'Sundanese'),
  TesseractLanguage('swa', 'Swahili'),
  TesseractLanguage('swe', 'Swedish'),
  TesseractLanguage('syr', 'Syriac'),
  TesseractLanguage('tgk', 'Tajik'),
  TesseractLanguage('tam', 'Tamil'),
  TesseractLanguage('tat', 'Tatar'),
  TesseractLanguage('tel', 'Telugu'),
  TesseractLanguage('tha', 'Thai'),
  TesseractLanguage('bod', 'Tibetan'),
  TesseractLanguage('tir', 'Tigrinya'),
  TesseractLanguage('ton', 'Tongan'),
  TesseractLanguage('tur', 'Turkish'),
  TesseractLanguage('uig', 'Uyghur'),
  TesseractLanguage('ukr', 'Ukrainian'),
  TesseractLanguage('urd', 'Urdu'),
  TesseractLanguage('uzb', 'Uzbek'),
  TesseractLanguage('uzb_cyrl', 'Uzbek (Cyrillic)'),
  TesseractLanguage('vie', 'Vietnamese'),
  TesseractLanguage('cym', 'Welsh'),
  TesseractLanguage('yid', 'Yiddish'),
  TesseractLanguage('yor', 'Yoruba'),
  TesseractLanguage('hye', 'Armenian'),
];

/// Best-effort mapping from a Tesseract language code to a BCP-47 locale
/// flutter_tts / the device's TTS engine understands, so switching the OCR
/// language also switches which voice reads the text back — reading Urdu
/// text in an English voice would be close to unintelligible. Falls back to
/// English if the code has no known mapping or the device has no matching
/// voice installed (flutter_tts silently falls back to its default voice
/// in that case).
String ttsLocaleFor(String tesseractCode) {
  const map = {
    'eng': 'en-US',
    'ara': 'ar-SA',
    'urd': 'ur-PK',
    'fas': 'fa-IR',
    'hin': 'hi-IN',
    'ben': 'bn-BD',
    'pan': 'pa-IN',
    'guj': 'gu-IN',
    'mar': 'mr-IN',
    'tam': 'ta-IN',
    'tel': 'te-IN',
    'kan': 'kn-IN',
    'mal': 'ml-IN',
    'sin': 'si-LK',
    'nep': 'ne-NP',
    'fra': 'fr-FR',
    'deu': 'de-DE',
    'spa': 'es-ES',
    'por': 'pt-PT',
    'ita': 'it-IT',
    'nld': 'nl-NL',
    'rus': 'ru-RU',
    'ukr': 'uk-UA',
    'pol': 'pl-PL',
    'ces': 'cs-CZ',
    'ron': 'ro-RO',
    'ell': 'el-GR',
    'tur': 'tr-TR',
    'heb': 'he-IL',
    'jpn': 'ja-JP',
    'kor': 'ko-KR',
    'chi_sim': 'zh-CN',
    'chi_tra': 'zh-TW',
    'vie': 'vi-VN',
    'tha': 'th-TH',
    'ind': 'id-ID',
    'msa': 'ms-MY',
    'swa': 'sw-KE',
    'amh': 'am-ET',
  };
  return map[tesseractCode] ?? 'en-US';
}