// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5EH1d5PaARrUo9c2wnp5r-I89KA0DlWY',
    appId: '1:248593836318:web:df59f57e8de7992ade810f',
    messagingSenderId: '248593836318',
    projectId: 'medisense-7144b',
    authDomain: 'medisense-7144b.firebaseapp.com',
    storageBucket: 'medisense-7144b.firebasestorage.app',
    measurementId: 'G-F542J3ECVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3O-aMxP5sJTtsxeBJkv0a-p6QeJ-RWwY',
    appId: '1:248593836318:android:f48e585f0bb8a21cde810f',
    messagingSenderId: '248593836318',
    projectId: 'medisense-7144b',
    storageBucket: 'medisense-7144b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeWAoauGDTszPf-Rbw-utAzYQnMN8EKPQ',
    appId: '1:248593836318:ios:a830e0145e899b4dde810f',
    messagingSenderId: '248593836318',
    projectId: 'medisense-7144b',
    storageBucket: 'medisense-7144b.firebasestorage.app',
    iosBundleId: 'com.medisense.medisenseApp',
  );
}
